In [2]:
import pandas as pd
import numpy as np
import nltk
nltk.download('punkt')
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from textblob import TextBlob
from sklearn.metrics import confusion_matrix, accuracy_score

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...


In [4]:
df_amazon = pd.read_json(r'C:\Users\harsh\Documents\MPSTME\Sem VI\NLP\Office_Products_5.json', lines=True)
df_twitter = pd.read_csv(r'C:\Users\harsh\Documents\MPSTME\Sem VI\NLP\full-corpus.csv')
df_twitter=df_twitter[df_twitter['Sentiment']!='irrelevant']

In [5]:
def sentiment_pol(text):
  blob = TextBlob(text)
  for sentence in blob.sentences:
    val=(sentence.sentiment.polarity)
    if val > 0.0:
      return "positive"
    elif val < 0.0:
      return "negative"
    else:
      return "neutral"

In [6]:
df_twitter['Sentiment Blob']=df_twitter['TweetText'].apply(sentiment_pol)
df_amazon['Sentiment Blob']=df_amazon['reviewText'].apply(sentiment_pol)

In [7]:
def sentiment_int(text):
  sia = SentimentIntensityAnalyzer()
  sp = sia.polarity_scores(text)
  if sp['compound'] >= 0.05:
    return "positive"
  elif sp['compound'] <= -0.05:
    return "negative"
  else:
    return "neutral"

In [8]:
df_twitter['Sentiment SIA']=df_twitter['TweetText'].apply(sentiment_int)
df_amazon['Sentiment SIA']=df_amazon['reviewText'].apply(sentiment_int)

In [9]:
df_amazon.head()

reviewerID        asin         reviewerName helpful  \
0  A32T2H8150OJLU  B00000JBLH                  ARH  [3, 4]   
1  A3MAFS04ZABRGO  B00000JBLH     Let it Be "Alan"  [7, 9]   
2  A1F1A0QQP2XVH5  B00000JBLH               Mark B  [3, 3]   
3   A49R5DBXXQDE5  B00000JBLH         R. D Johnson  [7, 8]   
4  A2XRMQA6PJ5ZJ8  B00000JBLH  Roger J. Buffington  [0, 0]   

                                          reviewText  overall  \
0  I bought my first HP12C in about 1984 or so, a...        5   
1  WHY THIS BELATED REVIEW? I feel very obliged t...        5   
2  I have an HP 48GX that has been kicking for mo...        2   
3  I've started doing more finance stuff recently...        5   
4  For simple calculations and discounted cash fl...        5   

                                             summary  unixReviewTime  \
0            A solid performer, and long time friend      1094169600   
1  Price of GOLD is up, so don't bury the golden ...      1197676800   
2   Good functionality, but not durable like old HPs      1293840000   
3       One of the last of an almost extinct species      1145404800   
4                                     Still the best      1375574400   

    reviewTime Sentiment Blob Sentiment SIA  
0   09 3, 2004       positive      positive  
1  12 15, 2007        neutral      positive  
2   01 1, 2011       positive      negative  
3  04 19, 2006       positive      positive  
4   08 4, 2013       positive      positive

In [10]:
df_twitter.head()

Topic Sentiment             TweetId                       TweetDate  \
0  apple  positive  126415614616154112  Tue Oct 18 21:53:25 +0000 2011   
1  apple  positive  126404574230740992  Tue Oct 18 21:09:33 +0000 2011   
2  apple  positive  126402758403305474  Tue Oct 18 21:02:20 +0000 2011   
3  apple  positive  126397179614068736  Tue Oct 18 20:40:10 +0000 2011   
4  apple  positive  126395626979196928  Tue Oct 18 20:34:00 +0000 2011   

                                           TweetText Sentiment Blob  \
0  Now all @Apple has to do is get swype on the i...        neutral   
1  @Apple will be adding more carrier support to ...       positive   
2  Hilarious @youtube video - guy does a duet wit...       positive   
3  @RIM you made it too easy for me to switch to ...       positive   
4  I just realized that the reason I got into twi...       positive   

  Sentiment SIA  
0       neutral  
1      positive  
2      positive  
3      positive  
4      positive

In [11]:
blob_cm=confusion_matrix(df_twitter['Sentiment'],df_twitter['Sentiment Blob'])
sia_cm=confusion_matrix(df_twitter['Sentiment'],df_twitter['Sentiment SIA'])
blob_acc=accuracy_score(df_twitter['Sentiment'],df_twitter['Sentiment Blob'])
sia_acc=accuracy_score(df_twitter['Sentiment'],df_twitter['Sentiment SIA'])

In [12]:
print("Confusion matrix while using TextBlob Sentiment: \n",blob_cm)
print("Accuracy while using TextBlob Sentiment: ",blob_acc)

Confusion matrix while using TextBlob Sentiment: 
 [[ 178  260  134]
 [ 189 1339  805]
 [  34  195  290]]
Accuracy while using TextBlob Sentiment:  0.5277453271028038


In [13]:
print("Confusion matrix while using SIA: \n",sia_cm)
print("Accuracy while using SIA: ",sia_acc)

Confusion matrix while using SIA: 
 [[ 291  138  143]
 [ 302 1234  797]
 [  47   99  373]]
Accuracy while using SIA:  0.554322429906542
